apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis-exporter
  template:
    metadata:
      labels:
        app: auth-redis-exporter
    spec:
      containers:
        - name: auth-redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: auth-redis:6379
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 9121
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-exporter
spec:
  selector:
    app: auth-redis-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9121
      targetPort: 9121
