apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-exporter
  template:
    metadata:
      labels:
        app: auth-db-exporter
    spec:
      containers:
        - name: auth-db-exporter
          image: prometheuscommunity/postgres-exporter:v0.10.0
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:postgres@auth-db:5432/petshop?sslmode=disable"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 9187
            failureThreshold: 30
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-exporter
spec:
  selector:
    app: auth-db-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9187
      targetPort: 9187
