apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-db-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor-db-exporter
  template:
    metadata:
      labels:
        app: editor-db-exporter
    spec:
      containers:
        - name: editor-db-exporter
          image: prometheuscommunity/postgres-exporter:v0.10.0
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://editor:editor@editor-db:5432/editor-db?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: editor-db-exporter
spec:
  selector:
    app: editor-db-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9187
      targetPort: 9187
