apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: auth-db-exporter
        static_configs:
          - targets: ["auth-db-exporter:9187"]
      - job_name: editor-db-exporter
        static_configs:
          - targets: [ "editor-db-exporter:9187" ]
      - job_name: signer-db-exporter
        static_configs:
          - targets: [ "signer-db-exporter:9187" ]
      - job_name: auth-redis-exporter
        static_configs:
          - targets: ["auth-redis-exporter:9121" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-db-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-db-prometheus
  template:
    metadata:
      labels:
        app: monitoring-db-prometheus
    spec:
      containers:
        - name: monitoring-db-prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 9090
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-db-prometheus
spec:
  selector:
    app: monitoring-db-prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi