apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: signer-app-autoscale
  name: signer-app-hpa
  namespace: default
spec:
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: signer-app
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: signer-app
  name: signer-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: signer-app
  template:
    metadata:
      labels:
        app: signer-app
    spec:
      containers:
        - image: signer-app
          imagePullPolicy: Never
          name: signer-app
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: signer-db-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: signer-db-config
                  key: postgres_password
            - name: CONFIG_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_host
            - name: CONFIG_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_port
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_profile
            - name: CONFIG_URL
              value: "http://$(CONFIG_APP_NAME):$(CONFIG_APP_PORT)"
            - name: OTEL_SERVICE_NAME
              value: signer-app
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: JAEGER_NAME
              valueFrom:
                configMapKeyRef:
                  key: host-name
                  name: jaeger-config
            - name: OTEL_TRACES_EXPORTER
              value: "$(JAEGER_NAME)"
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: jaeger-config
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://$(JAEGER_NAME):$(JAEGER_PORT)"
          resources:
            requests:
              cpu: 100m
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: signer-app
  name: signer-app
  namespace: default
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: signer-app
  type: ClusterIP