apiVersion: v1
kind: ConfigMap
metadata:
  name: editor-db-config
  namespace: default
data:
  postgres_user: 'editor'
  postgres_password: 'editor'
  postgres_db: 'editor-db'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: max-connections
  namespace: default
data:
  max-connections.sql: "ALTER SYSTEM SET max_connections = 500;"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: editor-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-db
spec:
  selector:
    matchLabels:
      app: editor-db
  template:
    metadata:
      labels:
        app: editor-db
    spec:
      volumes:
        - name: editor-db-storage
          persistentVolumeClaim:
            claimName: editor-db-pv-claim
        - name: max-connections
          configMap:
            name: max-connections
      containers:
        - image: postgres:15
          name: editor-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: editor-db-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: editor-db-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: editor-db-config
                  key: postgres_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: editor-db
          readinessProbe:
            exec:
              command: [
                        'psql', 'editor',
                        '-U', 'editor',
                        '-d', 'editor-db',
                        '-c', 'SELECT 1'
              ]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          volumeMounts:
            - name: editor-db-storage
              mountPath: /var/lib/postgresql/data
            - name: max-connections
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: editor-db
  name: editor-db
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: editor-db