version: "3.9"

networks:
  graylog-network:
    name: graylog-network

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.2
    volumes:
      - ./mongodb/mongo_data:/data/db
    restart: "no"
    networks:
      - graylog-network
    healthcheck:
      test: mongosh --norc --quiet --host=localhost:27017 --eval "db.getMongo()"
      interval: 10s
      timeout: 30s
      retries: 5
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.10.0
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch/opch_data:/usr/share/opensearch/data
    restart: "no"
    networks:
      - graylog-network
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      mongodb:
        condition: service_healthy
  graylog:
    container_name: graylog
    image: graylog/graylog:5.0
    volumes:
      - ./graylog/gr_data:/usr/share/graylog/data/data
      - ./graylog/gr_journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_ROOT_USERNAME: ${GRAYLOG_ROOT_USERNAME}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_USERNAME: ${GRAYLOG_USERNAME}
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    restart: "no"
    networks:
      - graylog-network
    healthcheck:
      test: curl --silent -f http://127.0.0.1:9000/api
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      opensearch:
        condition: service_healthy