apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}
spec:
  selector:
    app: {{.Values.app_name}}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.containers.port}}
      targetPort: {{.Values.containers.port}}